### ISSUE TITLE
Exclamation mark is atext, but not allowed

### ISSUE THREAD

**Issue by schulzrinne** [mmucklo/email-parse#22]
According to RFC 5322, page 12, ! is in the list of allowed characters for atext, but the library doesn't allow it. There's text in the source, but this may apply to the address-spec part:

// Note: check for Exim-banned characters   
                    //  See Bug #18749 - Unhandled Exception: 550 Restricted characters in address
                    if ($curChar == '%' || $curChar == '!') 

but this makes perfectly valid display names fail.

**Comment by mmucklo** [comment]
So there was a bug/feature in Exim a while back that would cause addresses with those characters to fail. I'm not sure if it was fixed or not. I could make that code optional, I suppose, unless you have a better suggestion?

**Comment by schulzrinne** [comment]
There are probably two roles for parsers such as yours: check new email
addresses provided by users (where "exotic" addresses are a bad idea) and
parsing and validating email addresses found "in the wild", e.g., on
incoming messages. I was assuming your library was more for the latter,
i.e., valid email addresses should be recognized and parsed as such, even
if exim may not like them. I'm not sure how rejecting a valid email address
in (say) an incoming email would be helpful, even if it triggers an old
exim bug. Thus, unless I'm missing a reason, the default should probably be
"accept anything that meets RFC 5322".

**Comment by etsibulko** [comment]
It would be great to fix this (or at least make it optional)

**Comment by mmucklo** [comment]
@etsibulko I can probably get to this within a few days or by the weekend.

**Comment by etsibulko** [comment]
@mmucklo that's a great news we appreciate it!

**Comment by mmucklo** [comment]
So I have an initial implementation in the "options" branch. I haven't yet written something for the singleton case, but using the constructor works.

**Comment by etsibulko** [comment]
@mmucklo, are you going to merge the "options' branch into "master" in future?

**Comment by mmucklo** [comment]
done.
